-- MySQL Script generated by MySQL Workbench
-- Mon Jul  9 16:33:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema emailsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emailsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emailsdb` DEFAULT CHARACTER SET utf8 ;
USE `emailsdb` ;

-- -----------------------------------------------------
-- Table `emailsdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emailsdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
