# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_ordered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
