# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20180717_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='commenters',
        ),
    ]
