# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_remove_message_commenters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
    ]
